fixup!

diff --git a/.github/workflows/commit-check-2.yml b/.github/workflows/commit-check-2.yml
--- a/.github/workflows/commit-check-2.yml
+++ b/.github/workflows/commit-check-2.yml
@@ -14,7 +14,18 @@ jobs:
     - name: Verify PR title with regex
       id: regex
       run: |
-        echo "Commits: ${{ steps.get-pr-commits.outputs.commits }}"
-        for variable in $(echo -e "${{ steps.get-pr-commits.outputs.commits }}"); do
+        for variable in ${{ steps.get-pr-commits.outputs.commits }}; do
           echo "commit: $variable"
         done
+#          echo "commit: ${{$variable.message}}"
+##          echo "$variable.message"
+##          regex='^(docs|fix|feat|build|ci|chore|perf|refactor|revert|style|test)(\([_0-9a-zA-Z-]+\))?: .+$'
+##            # Perform regex check and determine if title is correct
+##            if [[ $title =~ $regex ]]
+##            then
+##                echo "Title OK"
+##                exit 0
+##            else
+##                echo "Failing Title Check Test"
+##                exit 1
+##            fi
